### ISSUE TITLE
milestone script

### ISSUE THREAD

**Issue by kopardev** [CCBR/TaskManagement#1]
The script should:
- create new milestone with `+%Y-%m format` with `--due-date` == last day of the month
- create similar milestones retroactively for 2023 (and 2022)
- rename old weekly milestones to new monthly milestones
- delete old weekly milestones

**Comment by kopardev** [comment]
@slsevilla As you already have the script ... please deposit it here.

**Comment by slsevilla** [comment]
completed with commit 6565516

**Comment by kopardev** [comment]
@slsevilla I think you mean 08168ff

**Comment by kopardev** [comment]
Also added "delete" option [e61b7df](https://github.com/CCBR/TaskManagement/commit/e61b7dfd997bce573113bf43f3eaa058cfe62b6a)
